networks:
  mcp-net:
    name: mcp-net
    external: false

services:
  mcp-server:
    container_name: mcp-server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: server:latest
    networks:
      - mcp-net
    ports:
      - "8000:8000"
    env_file:
      - ./mcp_server/.env
    volumes:
      - ./mcp_server/app:/app/mcp_server/app  # Mount source code for hot-reload
      - ./logs/server:/app/mcp_server/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: no

  ai-client:
    container_name: ai-client
    build:
      context: .
      dockerfile: client.Dockerfile
    image: client:latest
    networks:
      - mcp-net
    ports:
      - "8503:8503"
    env_file:
      - ./ai_client/.env
    volumes:
      - ./ai_client/app:/app/ai_client/app  # Mount source code for hot-reload
      - ./logs/client:/app/ai_client/app/logs  # Must be after app mount to override
    command:
      uv run streamlit run app.py --server.port 8503 --server.baseUrlPath=/mcp --server.enableCORS=false --server.enableXsrfProtection=false --server.runOnSave=true
ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - mcp-server
    restart: no
